using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using Wenta;

namespace Wenta.Core.Tests
{
    /// <summary>Console parity runner: replays the CSV vectors generated by
    /// csharp/tools/gen_vectors.py against Wenta.Core and asserts equality.
    /// No xUnit/NuGet — runs with the same bare-csc toolchain as Wenta.Core.
    /// Exit code 0 = all green.</summary>
    internal static class Program
    {
        private static int _pass, _fail;

        private static void Main(string[] args)
        {
            string dir = args.Length > 0
                ? args[0]
                : Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "vectors");

            RunUnits(Path.Combine(dir, "units.csv"));
            RunFluid(Path.Combine(dir, "fluid.csv"));
            RunGeometry(Path.Combine(dir, "geometry.csv"));
            RunFriction(Path.Combine(dir, "friction.csv"));
            RunLosses(Path.Combine(dir, "losses.csv"));
            RunFlex(Path.Combine(dir, "flex.csv"));
            RunSizes(Path.Combine(dir, "sizes.csv"));
            RunFittings(Path.Combine(dir, "fittings.csv"));
            RunElbow(Path.Combine(dir, "elbow.csv"));
            RunSizing(Path.Combine(dir, "sizing.csv"));
            RunSolver(Path.Combine(dir, "solver.csv"));
            RunCatalog();
            RunBom();
            RunBalancing();
            RunRoom();

            Console.WriteLine();
            Console.WriteLine("==== " + _pass + " passed, " + _fail + " failed ====");
            Environment.ExitCode = _fail == 0 ? 0 : 1;
        }

        // ------------------------------------------------------------------

        private static readonly CultureInfo C = CultureInfo.InvariantCulture;
        private static readonly double[] _d = new double[8];

        private static string[] _cols;

        private static void ExpectError(bool error, string id, Action act)
        {
            if (!error) { act(); return; }
            try
            {
                act();
                Fail(id, "expected WentaException, got success");
            }
            catch (WentaException) { Pass(id); }
        }

        private static void Check(string id, double actual, double expected, double tol)
        {
            double denom = Math.Abs(expected) > 1.0 ? Math.Abs(expected) : 1.0;
            if (Math.Abs(actual - expected) <= tol * denom) Pass(id);
            else Fail(id, "got " + actual.ToString("R", C) + ", want "
                       + expected.ToString("R", C));
        }

        private static void CheckInt(string id, int actual, int expected)
        {
            if (actual == expected) Pass(id);
            else Fail(id, "got " + actual + ", want " + expected);
        }

        private static void Pass(string id) { _pass++; }

        private static void Fail(string id, string why)
        {
            _fail++;
            Console.WriteLine("FAIL " + id + ": " + why);
        }

        private static double[] Args(string joined)
        {
            string[] parts = joined.Split(',');
            var r = new double[parts.Length];
            for (int i = 0; i < parts.Length; i++)
                r[i] = double.Parse(parts[i], C);
            return r;
        }

        private static IEnumerable<string[]> Rows(string path)
        {
            using (var sr = new StreamReader(path))
            {
                string header = sr.ReadLine(); // skip
                string line;
                while ((line = sr.ReadLine()) != null)
                {
                    if (line.Length == 0) continue;
                    _cols = line.Split(';');
                    yield return _cols;
                }
            }
        }

        private static double E1 { get { return double.Parse(_cols[_cols.Length - 2], C); } }
        private static bool IsError
        {
            get { return _cols.Length >= 1 && _cols[_cols.Length - 1] == "error"; }
        }

        // ------------------------------------------------------------------

        private static void RunUnits(string path)
        {
            foreach (string[] c in Rows(path))
            {
                string id = c[0], op = c[1];
                double a = 0.0;
                if (op != "ach") a = double.Parse(c[2], C);
                switch (op)
                {
                    case "ach":
                        double[] aa = Args(c[2]);
                        ExpectError(IsError, id, delegate
                        {
                            Check(id, Units.AirChangesPerHour(aa[0], aa[1]), E1, 1e-12);
                        });
                        break;
                    default:
                        double r = op == "cfm_to_m3s" ? Units.CfmToM3s(a)
                                  : op == "m3s_to_cfm" ? Units.M3sToCfm(a)
                                  : op == "inwc_to_pa" ? Units.InwcToPa(a)
                                  : op == "pa_to_inwc" ? Units.PaToInwc(a)
                                  : op == "ft_to_m" ? Units.FtToM(a)
                                  : op == "m_to_ft" ? Units.MToFt(a)
                                  : op == "in_to_m" ? Units.InToM(a)
                                  : op == "m_to_in" ? Units.MToIn(a)
                                  : op == "fpm_to_ms" ? Units.FpmToMs(a)
                                  : op == "ms_to_fpm" ? Units.MsToFpm(a)
                                  : op == "f_to_c" ? Units.FToC(a)
                                  : Units.CToF(a);
                        Check(id, r, E1, 1e-12);
                        break;
                }
            }
        }

        private static void RunFluid(string path)
        {
            foreach (string[] c in Rows(path))
            {
                double[] a = Args(c[2]);
                ExpectError(IsError, c[0], delegate
                {
                    Fluid f = Fluid.AirAtAltitude(a[0], a.Length > 1 ? a[1] : 20.0);
                    Check(c[0], f.Density, double.Parse(c[3], C), 1e-12);
                    Check(c[0], f.DynamicViscosity, double.Parse(c[4], C), 1e-12);
                });
            }
        }

        private static void RunGeometry(string path)
        {
            foreach (string[] c in Rows(path))
            {
                double[] a = Args(c[2]);
                switch (c[1])
                {
                    case "round":
                        ExpectError(IsError, c[0], delegate
                        {
                            Round r = new Round(a[0]);
                            Check(c[0], r.Area, double.Parse(c[3], C), 1e-12);
                            Check(c[0], r.HydraulicDiameter, double.Parse(c[4], C), 1e-12);
                        });
                        break;
                    case "rect":
                        ExpectError(IsError, c[0], delegate
                        {
                            Rectangular r = new Rectangular(a[0], a[1]);
                            Check(c[0], r.Area, double.Parse(c[3], C), 1e-12);
                            Check(c[0], r.HydraulicDiameter, double.Parse(c[4], C), 1e-12);
                        });
                        break;
                    case "eq_round":
                        ExpectError(IsError, c[0], delegate
                        {
                            Check(c[0], Geometry.EquivalentRoundDiameter(a[0], a[1]),
                                  double.Parse(c[3], C), 1e-12);
                        });
                        break;
                }
            }
        }

        private static void RunFriction(string path)
        {
            foreach (string[] c in Rows(path))
            {
                double[] a = Args(c[2]);
                double r = 0.0;
                switch (c[1])
                {
                    case "reynolds": r = Friction.Reynolds(a[0], a[1], a[2]); break;
                    case "rel_rough": r = Friction.RelativeRoughness(a[0], a[1]); break;
                    case "friction_factor": r = Friction.FrictionFactor(a[0], a[1]); break;
                    case "colebrook": r = Friction.FrictionFactorColebrook(a[0], a[1]); break;
                }
                Check(c[0], r, E1, 1e-12);
            }
        }

        private static void RunLosses(string path)
        {
            foreach (string[] c in Rows(path))
            {
                double[] a = Args(c[2]);
                double r = c[1] == "straight"
                    ? Losses.StraightPressureDrop(a[0], a[1], a[2], a[3], a[4])
                    : Losses.LocalPressureDrop(a[0], a[1], a[2]);
                Check(c[0], r, E1, 1e-12);
            }
        }

        private static void RunFlex(string path)
        {
            foreach (string[] c in Rows(path))
            {
                double[] a = Args(c[2]);
                Check(c[0], Flex.StretchCorrectionFactor(a[0], a[1]), E1, 1e-12);
            }
        }

        private static void RunSizes(string path)
        {
            foreach (string[] c in Rows(path))
            {
                // arg is "<d>,<True|False>"; expected is c[3]
                string[] parts = c[2].Split(',');
                CheckInt(c[0],
                    StandardSizes.NearestRoundSize(
                        double.Parse(parts[0], C),
                        parts[1].Equals("True", StringComparison.OrdinalIgnoreCase)),
                    (int)double.Parse(c[3], C));
            }
        }

        private static void RunFittings(string path)
        {
            foreach (string[] c in Rows(path))
            {
                string id = c[0];
                double[] a = c[1] == "mitered" ? new double[0] : Args(c[2]);
                switch (c[1])
                {
                    case "reducer":
                        ExpectError(IsError, id, delegate
                        { Check(id, FittingsLibrary.ReducerRound(a[0], a[1], a[2]), D(c[3]), 1e-12); });
                        break;
                    case "expander":
                        ExpectError(IsError, id, delegate
                        { Check(id, FittingsLibrary.ExpanderRound(a[0], a[1], a[2]), D(c[3]), 1e-12); });
                        break;
                    case "tee_branch":
                        FittingsLibrary.JunctionTeeBranch(a[0], a[1], a[2], a[3],
                            out double z1, out double z2);
                        Check(id, z1, D(c[3]), 1e-12);
                        Check(id, z2, D(c[4]), 1e-12);
                        break;
                    case "tee_combine":
                        FittingsLibrary.JunctionTeeCombine(a[0], a[1], a[2], a[3],
                            out double k1, out double k2);
                        Check(id, k1, D(c[3]), 1e-12);
                        Check(id, k2, D(c[4]), 1e-12);
                        break;
                    case "damper":
                        ExpectError(IsError, id, delegate
                        { Check(id, FittingsLibrary.DamperButterfly(a[0]), D(c[3]), 1e-12); });
                        break;
                    case "diffuser":
                        Check(id, FittingsLibrary.DiffuserCeiling(a[0]), D(c[3]), 1e-12);
                        break;
                    case "grille":
                        ExpectError(IsError, id, delegate
                        { Check(id, FittingsLibrary.GrilleReturn(a[0]), D(c[3]), 1e-12); });
                        break;
                    case "rect_elbow":
                        Check(id, FittingsLibrary.RectangularElbow(a[0], a[1], a[2], a[3]),
                              D(c[3]), 1e-12);
                        break;
                    case "mitered":
                        string[] mp = c[2].Split(',');
                        ExpectError(IsError, id, delegate
                        {
                            Check(id, FittingsLibrary.MiteredElbow(
                                double.Parse(mp[0], C),
                                mp[1].Equals("True", StringComparison.OrdinalIgnoreCase)),
                                  D(c[3]), 1e-12);
                        });
                        break;
                }
            }
        }

        private static double D(string s)
        {
            return s.Length == 0 ? 0.0 : double.Parse(s, C);
        }

        private static void RunElbow(string path)
        {
            foreach (string[] c in Rows(path))
            {
                string id = c[0];
                double[] a = Args(c[2]);
                double r = a[0], d = a[1], ang = a[2];
                double tol = id.Contains("grid") ? 1e-9 : 2e-4;
                ExpectError(IsError, id, delegate
                {
                    Check(id, new ElbowRound(r, d, ang).Zeta(), D(c[3]), tol);
                });
            }
        }

        private static void RunSizing(string path)
        {
            foreach (string[] c in Rows(path))
            {
                string id = c[0];
                int comma = c[2].IndexOf(',');
                bool bad = IsError;
                double[] a = c[1] == "noise_limit"
                    ? new[] { double.Parse(c[2].Substring(0, comma), C) }
                    : Args(c[2]);
                int expectedIdx = bad ? 0 : (int)double.Parse(c[3], C);
                double expectedV = bad ? 0.0 : D(c[4]);
                double expectedDpm = bad ? 0.0 : D(c[5]);
                ExpectError(IsError, id, delegate
                {
                    Sizing.SizingResult r;
                    switch (c[1])
                    {
                        case "velocity_round":
                            r = Sizing.VelocityMethod(a[0], Sizing.ShapeRound, a[1]);
                            Check(id, r.Velocity, expectedV, 1e-12);
                            CheckInt(id, RoundIndex((Round)r.Section), expectedIdx);
                            return;
                        case "velocity_rect":
                            r = Sizing.VelocityMethod(a[0], Sizing.ShapeRectangular, a[1]);
                            Check(id, r.Velocity, expectedV, 1e-12);
                            CheckInt(id, RectIndex((Rectangular)r.Section), expectedIdx);
                            return;
                        case "equal_friction":
                            r = Sizing.EqualFrictionMethod(a[0], a[1], Sizing.ShapeRound);
                            Check(id, r.Velocity, expectedV, 1e-12);
                            Check(id, r.PressureDropPerMeter, expectedDpm, 1e-12);
                            CheckInt(id, RoundIndex((Round)r.Section), expectedIdx);
                            return;
                        case "equal_friction_rect":
                            r = Sizing.EqualFrictionMethod(a[0], a[1], Sizing.ShapeRectangular);
                            Check(id, r.Velocity, expectedV, 1e-12);
                            Check(id, r.PressureDropPerMeter, expectedDpm, 1e-12);
                            CheckInt(id, RectIndex((Rectangular)r.Section), expectedIdx);
                            return;
                        case "noise_limit":
                            r = Sizing.NoiseLimitMethod(a[0], c[2].Substring(comma + 1));
                            Check(id, r.Velocity, expectedV, 1e-12);
                            CheckInt(id, RoundIndex((Round)r.Section), expectedIdx);
                            return;
                        case "aspect":
                            r = Sizing.AspectRatioMethod(a[0], a[1], a[2]);
                            Check(id, r.Velocity, expectedV, 1e-12);
                            CheckInt(id, RectIndex((Rectangular)r.Section), expectedIdx);
                            return;
                    }
                });
            }
        }

        private static int RoundIndex(Round s)
        {
            return Array.IndexOf(StandardSizes.RoundDuctSizes, (int)Math.Round(s.Diameter * 1000.0));
        }

        private static int RectIndex(Rectangular s)
        {
            int w = (int)Math.Round(s.Width * 1000.0), h = (int)Math.Round(s.Height * 1000.0);
            int[][] table = StandardSizes.RectangularDuctSizes;
            for (int i = 0; i < table.Length; i++)
                if (table[i][0] == w && table[i][1] == h) return i;
            return -1;
        }

        // ---- solver networks (mirror of gen_vectors.py mirror_*_net) ----

        private static void RunSolver(string path)
        {
            foreach (string[] c in Rows(path))
            {
                string id = c[0];
                if (id == "net_readme")
                {
                    var net = new Network { Name = "readme" };
                    net.Add("ahu", new Source("AHU"));
                    net.Add("duct", new RigidDuct("duct", new Round(0.2), 20.0));
                    net.Add("term", new Terminal("terminal", 0.1));
                    net.Connect("ahu", "duct");
                    net.Connect("duct", "term");
                    double dp = net.Solve();
                    Check(id, dp, D(c[3]), 1e-12);
                    Port inlet = net.Components["duct"].Port_("inlet");
                    Check(id, inlet.Flowrate ?? 0.0, D(c[4]), 1e-12);
                    Check(id, inlet.PressureDrop, D(c[5]), 1e-12);
                }
                else if (id == "net_tee")
                {
                    var net = new Network { Name = "tee" };
                    net.Add("ahu", new Source("AHU"));
                    net.Add("duct", new RigidDuct("duct", new Round(0.315), 20.0));
                    net.Add("tee", new Tee("tee", new Round(0.315), 0.1, 0.4));
                    net.Add("d2", new RigidDuct("d2", new Round(0.2), 5.0));
                    net.Add("flex", new FlexDuct("flex", 0.125, 3.0, 2.0, 100.0));
                    net.Add("t1", new Terminal("t1", 0.06));
                    net.Add("t2", new Terminal("t2", 0.04));
                    net.Connect("ahu", "duct");
                    net.Connect("duct", "tee");
                    net.Connect("tee.straight", "d2");
                    net.Connect("tee.branch", "flex");
                    net.Connect("d2", "t1");
                    net.Connect("flex", "t2");
                    double dp = net.Solve();
                    Check(id, dp, D(c[3]), 1e-12);
                    Check(id, net.Components["duct"].Port_("inlet").Flowrate ?? 0.0, D(c[4]), 1e-12);
                    Check(id, net.Components["tee"].Port_("straight").Flowrate ?? 0.0, D(c[5]), 1e-12);
                    Check(id, net.Components["tee"].Port_("branch").Flowrate ?? 0.0, D(c[6]), 1e-12);
                }
            }
        }

        // ---- Catalog (open ζ-catalog JSON) — Phase-1 “new” module ----
        // Self-contained: parses the shipped example catalogue inline and
        // asserts documented behaviours (ById, size-window Match, ζ, and
        // the correlation fallback for types the catalogue does not carry).
        // The fallback values are the same Vettora.FittingsLibrary already
        // vector-tested in fittings.csv, so they stay independent of the
        // catalogue data itself.
        private static void RunCatalog()
        {
            string json =
                "{\n" +
                "  \"name\": \"example-generic-rect\",\n" +
                "  \"version\": 1,\n" +
                "  \"fittings\": [\n" +
                "    {\"id\":\"rect-elbow-r1.5\",\"type\":\"rect_elbow\"," +
                "     \"size_min_mm\":[100,100],\"size_max_mm\":[1200,2000]," +
                "     \"zeta\":0.17,\"source\":\"Hendiger tab. 4.2 (R=1.5W)\"," +
                "     \"knr\":\"KNR 2-08 03xx\"},\n" +
                "    {\"id\":\"rect-elbow-r1.0\",\"type\":\"rect_elbow\"," +
                "     \"size_min_mm\":[100,100],\"size_max_mm\":[1200,2000]," +
                "     \"zeta\":0.21,\"source\":\"Hendiger tab. 4.2 (R=1.0W)\"," +
                "     \"knr\":\"KNR 2-08 03xx\"},\n" +
                "    {\"id\":\"round-elbow-r1.0\",\"type\":\"round_elbow\"," +
                "     \"zeta\":0.24,\"source\":\"Hendiger tab. 4.3 (R/D=1.0)\"," +
                "     \"knr\":\"KNR 2-08 03xx\"},\n" +
                "    {\"id\":\"tee-branch-typical\",\"type\":\"tee\"," +
                "     \"zeta\":0.45,\"source\":\"generic branch tee\"," +
                "     \"knr\":\"KNR 2-08 03xx\"},\n" +
                "    {\"id\":\"vav-box\",\"type\":\"damper\"," +
                "     \"size_min_mm\":[100],\"size_max_mm\":[630]," +
                "     \"zeta\":0.35,\"source\":\"generic VAV box fully open\"," +
                "     \"knr\":\"KNR 2-08 04xx\"}\n" +
                "  ]\n" +
                "}";
            ZetaCatalog cat = ZetaCatalog.Parse(json, "inline");

            CheckInt("cat_count", cat.Fittings.Count, 5);
            Check("cat_name", cat.Name == "example-generic-rect" ? 1.0 : 0.0, 1.0, 1e-12);
            CheckInt("cat_version", cat.Version, 1);

            // ById
            ZetaCatalog.CatalogEntry vav = cat.ById("vav-box");
            Check("cat_byid_zeta", vav.Zeta, 0.35, 1e-12);
            Check("cat_byid_source",
                vav.Source == "generic VAV box fully open" ? 1.0 : 0.0, 1.0, 1e-12);
            Check("cat_byid_knr", vav.Knr.Length > 0 ? 1.0 : 0.0, 1.0, 1e-12);
            Check("cat_byid_missing", cat.ById("nope") == null ? 1.0 : 0.0, 1.0, 1e-12);

            // Match: first windowed entry wins for a size inside the window.
            Check("cat_match_rect", cat.Match("rect_elbow", new[]{ 400.0, 200.0 }).Zeta, 0.17, 1e-12);
            // Outside every window → no match.
            Check("cat_match_outside", cat.Match("rect_elbow", new[]{ 2000.0, 3000.0 }) == null ? 1.0 : 0.0, 1.0, 1e-12);
            // No size window → matches any size of that type.
            Check("cat_match_nowindow", cat.Match("round_elbow", new[]{ 315.0 }).Zeta, 0.24, 1e-12);

            // ZetaFor: catalogue wins over correlation when present.
            Check("cat_zeta_catalog", cat.ZetaFor("tee", new double[0]), 0.45, 1e-12);
            // ZetaFor fallback: type not in catalogue → correlation library.
            // GrilleReturn(0.15) = 0.2875 (see fittings.csv grl0.15).
            Check("cat_zeta_fallback", cat.ZetaFor("grille", new[]{ 300.0 }), 0.2875, 1e-12);
            // No entry and no correlation → error.
            ExpectError(true, "cat_zeta_unknown", delegate { cat.ZetaFor("nonsense", new double[0]); });
        }

        // ---- Bom (bill of materials + KNR rows) — Phase-1 “new” module ----
        // Mirrors the net_tee network from RunSolver and asserts the parts list:
        // one row per component, straight-duct length + π·D·L sheet area, and
        // the KNR codes. Expected geometry is computed independently from thin-air.
        private static void RunBom()
        {
            var net = new Network { Name = "bom-tee" };
            net.Add("ahu", new Source("AHU"));
            net.Add("duct", new RigidDuct("duct", new Round(0.315), 20.0));
            net.Add("tee", new Tee("tee", new Round(0.315), 0.1, 0.4));
            net.Add("d2", new RigidDuct("d2", new Round(0.2), 5.0));
            net.Add("flex", new FlexDuct("flex", 0.125, 3.0, 2.0, 100.0));
            net.Add("t1", new Terminal("t1", 0.06));
            net.Add("t2", new Terminal("t2", 0.04));
            net.Connect("ahu", "duct");
            net.Connect("duct", "tee");
            net.Connect("tee.straight", "d2");
            net.Connect("tee.branch", "flex");
            net.Connect("d2", "t1");
            net.Connect("flex", "t2");
            net.Solve();

            Bom bom = Bom.Build(net);
            CheckInt("bom_rows", bom.Rows.Count, 7);

            // Straight-duct paths carry sheet area A = π·(D/2)²·L, in m².
            Bom.BomRow duct = FindBom(bom, "duct");
            CrossSection cs = new Round(0.315);
            Check("bom_duct_length", duct.Length, 20.0, 1e-12);
            Check("bom_duct_area", duct.Area, cs.Area * 20.0, 1e-12);
            Check("bom_duct_kind", duct.Kind == "duct" ? 1.0 : 0.0, 1.0, 1e-12);
            Check("bom_duct_knr", duct.KnrCode.Length > 0 ? 1.0 : 0.0, 1.0, 1e-12);

            Bom.BomRow d2 = FindBom(bom, "d2");
            Check("bom_d2_area", d2.Area, Math.PI * (0.2 / 2.0) * (0.2 / 2.0) * 5.0, 1e-12);

            Bom.BomRow flex = FindBom(bom, "flex");
            Check("bom_flex_length", flex.Length, 3.0, 1e-12);
            Check("bom_flex_area", flex.Area, Math.PI * (0.125 / 2.0) * (0.125 / 2.0) * 3.0, 1e-12);
            Check("bom_flex_kind", flex.Kind == "flex" ? 1.0 : 0.0, 1.0, 1e-12);

            // Non-duct items carry zero length/area; source has no KNR code.
            Check("bom_source_len", FindBom(bom, "ahu").Length, 0.0, 1e-12);
            Check("bom_source_knr_empty", FindBom(bom, "ahu").KnrCode.Length == 0 ? 1.0 : 0.0, 1.0, 1e-12);
            Check("bom_terminal_kind", FindBom(bom, "t1").Kind == "terminal" ? 1.0 : 0.0, 1.0, 1e-12);
            Check("bom_fitting_kind", FindBom(bom, "tee").Kind == "fitting" ? 1.0 : 0.0, 1.0, 1e-12);

            double len = cs.Area * 20.0 + Math.PI * (0.2 / 2.0) * (0.2 / 2.0) * 5.0
                       + Math.PI * (0.125 / 2.0) * (0.125 / 2.0) * 3.0;
            Check("bom_total_length", bom.TotalLength, 28.0, 1e-12);
            Check("bom_total_area", bom.TotalArea, len, 1e-12);

            // CSV: header + 7 data rows (8 lines each terminated by \r\n).
            string csv = bom.ToCsv();
            int lines = 0;
            for (int i = 0; i < csv.Length; i++)
                if (csv[i] == '\n') lines++;
            Check("bom_csv_lines", lines == 8 ? 1.0 : 0.0, 1.0, 1e-12);
        }

        // ---- Balancing (damper ζ + setting) — Phase-4 “balancing” vertical ----
        // Mirrors venti/src/balancing.rs closed-form tests: required ζ from the
        // dynamic-pressure relation, the surplus-Δ logic, and the open-%
        // round-trip through the (already vector-tested) DamperButterfly.
        private static void RunBalancing()
        {
            // required_zeta: ζ = 2·dp/(ρ v²). ρ=1.204, v=4 → dynamic=9.632.
            Check("bal_zeta_closed", Balancing.RequiredZeta(9.632, 4.0, 1.204), 1.0, 1e-12);
            // The induced drop round-trips through LocalPressureDrop.
            Check("bal_roundtrip",
                Losses.LocalPressureDrop(Balancing.RequiredZeta(9.632, 4.0, 1.204), 4.0, 1.204),
                9.632, 1e-12);
            // Zero dynamic pressure guard.
            Check("bal_zero_dynamic", Balancing.RequiredZeta(5.0, 0.0, 1.204), 0.0, 1e-12);

            // balancing_zeta: short by 19.264 Pa at dynamic 9.632 → ζ = 2.
            Check("bal_delta", Balancing.BalancingZeta(30.0, 10.736, 4.0, 1.204), 2.0, 1e-12);
            // Branch already meets / exactly met → 0 (fully open).
            Check("bal_already_met", Balancing.BalancingZeta(10.0, 20.0, 4.0, 1.204), 0.0, 1e-12);
            Check("bal_exact", Balancing.BalancingZeta(10.0, 10.0, 4.0, 1.204), 0.0, 1e-12);
            // The added ζ reproduces the missing drop.
            double z = Balancing.BalancingZeta(30.0, 10.736, 4.0, 1.204);
            Check("bal_added_dp",
                Losses.LocalPressureDrop(z, 4.0, 1.204), 30.0 - 10.736, 1e-9);

            // damper_open_percentage round-trips through DamperButterfly.
            double[] roundTripZetas = new double[] { 0.1, 0.5, 1.0, 2.5, 5.0, 8.0, 10.0 };
            for (int i = 0; i < roundTripZetas.Length; i++)
            {
                double zeta = roundTripZetas[i];
                double open = Balancing.DamperOpenPercentage(zeta);
                double back = FittingsLibrary.DamperButterfly(open);
                Check("bal_open_rt" + i, back, zeta, 1e-9);
            }
            // Below the fully-open floor → fully open → still ζ = 0.1.
            Check("bal_floor", Balancing.DamperOpenPercentage(0.05), 100.0, 1e-12);
            Check("bal_floor_rt",
                FittingsLibrary.DamperButterfly(Balancing.DamperOpenPercentage(0.1)), 0.1, 1e-12);
        }

        // ---- Room ventilation balance — Phase-4 “balancing” family ----
        // Mirrors venti/src/room.rs closed-form tests: net sign, tolerance,
        // ACH, imbalance fraction, totals, and CSV rendering.
        private static void RunRoom()
        {
            // Net sign.
            Check("room_net_over", new RoomBalance(0.3, 0.1).NetM3s(), 0.2, 1e-12);
            Check("room_net_under", new RoomBalance(0.1, 0.3).NetM3s(), -0.2, 1e-12);
            Check("room_net_equal", new RoomBalance(0.2, 0.2).NetM3s(), 0.0, 1e-12);

            // is_balanced tolerance (monotonic).
            RoomBalance bal = new RoomBalance(0.5, 0.25); // net 0.25
            Check("room_tol_low", bal.IsBalanced(0.249) ? 1.0 : 0.0, 0.0, 1e-12);
            Check("room_tol_eq", bal.IsBalanced(0.25) ? 1.0 : 0.0, 1.0, 1e-12);
            Check("room_tol_hi", bal.IsBalanced(0.251) ? 1.0 : 0.0, 1.0, 1e-12);

            // ACH via Units: 0.1 m³/s in 100 m³ = 3.6.
            Check("room_ach", Units.AirChangesPerHour(0.1, 100.0), 3.6, 1e-12);
            Check("room_ach_zero_flow", Units.AirChangesPerHour(0.0, 100.0), 0.0, 1e-12);
            ExpectError(true, "room_ach_bad_volume", delegate { Units.AirChangesPerHour(0.1, 0.0); });

            // Validation.
            ExpectError(true, "room_neg_supply", delegate { new RoomBalance(-0.1, 0.2); });
            ExpectError(true, "room_neg_exhaust", delegate { new RoomBalance(0.1, -0.2); });
            new RoomBalance(0.0, 0.0); // ok, no assert
            Check("room_zero_ok", 1.0, 1.0, 1e-12);

            // Imbalance fraction.
            Check("room_imb_pure_supply", new RoomBalance(0.3, 0.0).ImbalanceFraction() ?? 0.0, 1.0, 1e-12);
            Check("room_imb_pure_exhaust", new RoomBalance(0.0, 0.3).ImbalanceFraction() ?? 0.0, -1.0, 1e-12);
            Check("room_imb_balanced", new RoomBalance(0.2, 0.2).ImbalanceFraction() ?? 99.0, 0.0, 1e-12);
            Check("room_imb_half", new RoomBalance(0.5, 0.25).ImbalanceFraction() ?? 0.0, 0.5, 1e-12);
            Check("room_imb_none", new RoomBalance(0.0, 0.0).ImbalanceFraction() == null ? 1.0 : 0.0, 1.0, 1e-12);

            // Totals across rooms (binary-fraction-exact).
            RoomBalanceSet set = new RoomBalanceSet();
            set.Add("bathroom", new RoomBalance(0.0625, 0.125));
            set.Add("living", new RoomBalance(0.25, 0.125));
            set.Add("kitchen", new RoomBalance(0.0625, 0.1875));
            Check("room_tot_supply", set.TotalSupplyM3s(), 0.375, 1e-12);
            Check("room_tot_exhaust", set.TotalExhaustM3s(), 0.4375, 1e-12);
            Check("room_tot_net", set.OverallNetM3s(), -0.0625, 1e-12);
            Check("room_tot_bal_eq", set.IsBalanced(0.0625) ? 1.0 : 0.0, 1.0, 1e-12);
            Check("room_tot_bal_low", set.IsBalanced(0.0624) ? 1.0 : 0.0, 0.0, 1e-12);

            // CSV content (compact format, trailing zeros trimmed).
            RoomBalanceSet csvSet = new RoomBalanceSet();
            csvSet.AddWithVolume("bathroom", new RoomBalance(0.02, 0.05), 5.0);
            csvSet.Add("corridor", new RoomBalance(0.10, 0.10));
            string csv = csvSet.CsvRender();
            Check("room_csv_header", Contains(csv, "name,supply_m3s,exhaust_m3s,net_m3s,ach") ? 1.0 : 0.0, 1.0, 1e-12);
            Check("room_csv_row1", Contains(csv, "bathroom,0.02,0.05,-0.03,14.4") ? 1.0 : 0.0, 1.0, 1e-12);
            Check("room_csv_row2", Contains(csv, "corridor,0.1,0.1,0,") ? 1.0 : 0.0, 1.0, 1e-12);
        }

        private static bool Contains(string haystack, string needle)
        {
            return haystack.IndexOf(needle) >= 0;
        }

        private static Bom.BomRow FindBom(Bom bom, string id)
        {
            foreach (Bom.BomRow r in bom.Rows)
                if (r.ItemId == id) return r;
            throw new WentaException("bom row not found: " + id);
        }
    }
}

